### PR TITLE
Add support for `pnpm`

### PR DESCRIPTION
**Pull request by valerybugakov**
## Context

This PR adds support for `pnpm` workspaces. We're switching to `pnpm` to simplify our integration with Bazel. See the tracking issue for more context:
- https://github.com/sourcegraph/sourcegraph/issues/44909

## Test plan

1. Checkout to `vb/pnpm-test-3` in the Sourcegraph monorepo. 
2. `rm -rf node_modules ./client/*/node_modules && pnpm install`
3. `DIR=/path/to/scip-typescript; "$DIR/node_modules/.bin/ts-node" "$DIR/src/main.ts" index --pnpm-workspaces`

### CODE REVIEW

**Comment by valerybugakov** [comment]
Looks like the [CI / test (18.x)](https://github.com/sourcegraph/scip-typescript/actions/runs/3852887539/jobs/6565464436) job fails in [other PRs](https://github.com/sourcegraph/scip-typescript/pull/218) not related to the package logic too.

**Review by varungandhi-src — APPROVED** [review]

**Review by olafurpg — APPROVED** [review]

**Comment by olafurpg** [comment]
We can add an integration test by adding a pnpm project under `snapshots/input` and make sure to enable the new `--pnpm-workspaces` flag here https://github.com/sourcegraph/scip-typescript/blob/4834ff7eef11c0b664da8e54bb2741bcaab91b48/src/main.test.ts#L57

**Comment by valerybugakov** [comment]
@olafurpg, added https://github.com/sourcegraph/scip-typescript/pull/219/commits/56506add69930f153d7f51787963fc0902aef330 👍

**Comment by valerybugakov** [comment]
And fixed the issue with the [CI / test (18.x)](https://github.com/sourcegraph/scip-typescript/actions/runs/3852887539/jobs/6565464436) job.

**Pull request merged**
