### PR TITLE
Use the name scip-typescript in user-facing places.

### PR DESCRIPTION
**Pull request by varungandhi-src**
Makes progress towards https://github.com/sourcegraph/lsif-typescript/issues/128

I'll create a tag in a separate PR. One headache we're going to have is that
the automatic ChangeLog generation will link to non-existent PRs in this repo,
instead of linking to scip-typescript. I think we could try the `--between-tags`
option of `github-changes` though. Maybe that avoids the problem.

### Test plan

n/a

### CODE REVIEW

**Comment by varungandhi-src** [comment]
TODO: Indexer name in output should be `scip-typescript`.

**Review by olafurpg — COMMENTED** [review]
We should update the indexer to use the `scip-typescript` scheme for symbols

**Comment by varungandhi-src** [comment]
Done.

**Review by olafurpg — APPROVED** [review]
LGTM 👍 Let's get this released to npm/Docker! It was a good idea to start by only renaming user-facing stuff.

**Pull request merged**
