### PR TITLE
Implement enclosing ranges

### PR DESCRIPTION
**Pull request by Titou325**
Implements basic `enclosing_ranges` for JS/TS.
The following are implemented:

* Named arrow function declaration,
* Function declaration,
* Class declaration,
* Method declaration,
* TS Interface declaration

To facilitate snapshot handling, I rebased the current snapshot formatter on the one used for Python. These two should be put in common at a later stage.

The implementation itself is very straightforward, and I believe can easily be extended to support other features.

Related to #278 

### Test plan

Added the following snapshots, with their input and output. The output was visually confirmed.

* Added `enclosing-range` snapshot to test JS support,
* Added `enclosing-range-ts` snapshot to test TS support

### CODE REVIEW

**Comment by maks-ivanov** [comment]
super glad this is being built!

**Comment by varungandhi-src** [comment]
Apologies for missing this PR earlier, I will review this PR on Monday. For future PRs, please feel free to ping me directly.

**Comment by varungandhi-src** [comment]
Overall, this PR looks quite good. I've broken it up into smaller PRs, and made some minor adjustments directly instead of bothering you with minor comments. There doesn't seem to be any performance degradation, so we can leave it on by default.

- https://github.com/sourcegraph/scip-typescript/pull/306
- https://github.com/sourcegraph/scip-typescript/pull/307
- https://github.com/sourcegraph/scip-typescript/pull/308

**Comment by varungandhi-src** [comment]
Closing this PR as it is superseded by https://github.com/sourcegraph/scip-typescript/pull/308

**Pull request closed without merging**
